# Generated by Django 3.1.2 on 2020-12-16 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20201216_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_snippet', to='snippets.project'),
        ),
    ]
